format = '''
[┌](bold blue) $hostname $directory $fill$python$git_branch$shell
[└─>](bold blue) '''


[hostname]
ssh_only = false
format = '[$hostname](bold red) [ ](blue) '
disabled = false



[python]
symbol = ''
pyenv_version_name = true
format = ' [${symbol} (\($virtualenv\) )]($style)'


[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

[fill]
symbol = ' '

[directory]
truncation_length = 12
truncation_symbol = '…/'
read_only = "  "
