plugin {
    hyprbars {
        # example config
        bar_height = 20

        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(ff4040), 18, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(eeee11), 18,  , hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(008b45), 18, , hyprctl dispatch movetoworkspacesilent special:magic
        bar_color = rgba(0, 0, 0, 0.8)
        bar_part_of_window = true
        bar_button_padding = 7
    }
    #Hyprspace {
     #   bind = ALT,tab, overview:toggle
      #  bind = ALT, tab, submap, overview
      #   submap = overview
    
       # bind = , k, workspace, +1
       # bind = , j, workspace, -1
       # bind = , Space, overview:toggle
       # bind = , Space, submap, reset
       # bind = , Escape, submap, reset
       # submap = reset
        
    #}
    overview {
        dragAlpha = 0.5
    }

   }
windowrulev2 = plugin:hyprbars:nobar,class:(firefox)
